version: '3'

services:
  rubick-shop:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    command: ["pnpm", "dev"]
    ports:
      - "3600:3600" # 你可以根据实际需要调整端口
